### PR TITLE
prepare monalisa to distribute it from pypi

### PR DESCRIPTION
**Pull request by 4383**
- introduce packaging by using `pyproject`;
- move python files into the `monalisa` module;
- introduce tox and prepare testing.

### CODE REVIEW

**Comment by 4383** [comment]
Please do some tests by following the readme instructions and let me know if everything works as expected.
Please, can you provide me some real examples of usages that I'd be able to use test it locally.

**Comment by 4383** [comment]
once merged, the next step will be to properly setup github actions and pypi account to deploy monalisa automatically from pypi and so to be able to install monalisa like this:

`pip install monalisa`

You will just have to push a new git tag to automatically create a new pypi version. Git driven workflow.

**Comment by 4383** [comment]
Thanks Nathan.
Now I'd suggest to you to setup a trusted publisher on Pypi => https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/

**Comment by 4383** [comment]
It will allow you to bind your github repo to your pypi account, and then you will be to publish your project in a fully automatized way

**Comment by 4383** [comment]
And, hence, your users will be able to pull monalisa as a classical python module.

**Comment by nathan-hoche** [comment]
Hi! Thank you for the commit!

I think you saw it, but I updated the readme to describe each argument, I also confirm that everything works well.

You can test it via: ```monalisa img/mona-lisa/mona.png 50 5```
But the image generated will not be near the objectif.

I will check for the pypi setup!

**Pull request merged**
