### PR TITLE
fix requirements versions

### PR DESCRIPTION
**Pull request by 4383**
Gates are failing with some requirements versions.... this commit should fix that.

### CODE REVIEW

**Comment by 4383** [comment]
workflow is triggering \o/

**Comment by 4383** [comment]
WTF???
`ERROR: No matching distribution found for numpy==2.1.3` 

https://pypi.org/project/numpy/2.1.3/

**Comment by 4383** [comment]
Well... I removed the requirements pin

**Comment by 4383** [comment]
Works better, but requirements are not pinned... Let's do that for now and fix it later

**Comment by 4383** [comment]
Once your pypi account is created and bound with your github account through OIDC, please create a git tag and push it to github:

```bash
$ git tag 0.1.0 # by example
$ git push --tags
```

It will trigger the mechanics, construct a new package and deploy it to pypi. Once done you will be able to install monalisa with pip: `pip install monalisa`.

And you will be able to update your readme file to document how to install monalisa from pypi:

https://github.com/nathan-hoche/MonaLisa/blob/ae06d0f47a98fb36a5c9a18f8e9961e490b37c2d/README.md?plain=1#L21

**Comment by nathan-hoche** [comment]
I'm still searching for that. I have the project in pending ('Pending publisher'), I added the tags and push via the command you put, but nothing change. Have you any idea?

**Comment by 4383** [comment]
I can see that you face failures https://github.com/nathan-hoche/MonaLisa/actions/runs/11974717420

**Comment by 4383** [comment]
Apparently you have naming issues with your project https://pypi.org/help/#project-name

**Comment by 4383** [comment]
I checked and I found no monalisa project on pypi https://pypi.org/search/?q=monalisa so maybe someone is squatting it... no luck... that could explain the failure.

**Comment by 4383** [comment]
Either you ping the pypi maintainers and try to discuss with them, or you rename it (or at least the python package) and knock on the wood.

**Pull request merged**
